name: Run tests
on: [push, pull_request]
jobs:
  rspec-tests:
    name: RSpec
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
          bundler-cache: true
      - name: Run tests
        run: bundler exec rspec
